on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    name: Validate
    runs-on: ubuntu-latest
    container:
      image: docker.io/endlessm/eos:master

    steps:
      - name: System dependencies
        run: |
          apt-get update
          apt-get install -y \
            appstream-util \
            flake8 \
            git \
            shellcheck
      - name: Checkout
        uses: actions/checkout@v3
      # FIXME: Drop this when checkout figures out that it should use
      # --system when it's running as root in a container.
      #
      # https://github.com/actions/checkout/issues/1169
      - name: Mark git checkout as safe directory
        run: |
          git config --system --add safe.directory "$GITHUB_WORKSPACE"
      - name: Lint programs
        run: |
          ./lint.sh
      - name: Validate AppStream
        run: |
          ./validate.sh
